FROM oven/bun:1-slim AS bun-build

WORKDIR /app

COPY ./frontend .

RUN bun i && bun run nuxt generate

FROM golang:alpine AS go-build

WORKDIR /app

COPY routes routes
COPY utils utils
COPY main.go go.mod go.sum ./
COPY --from=bun-build /app/.output/public ./frontend/.output/public

RUN go build -o main .

FROM gcr.io/distroless/static

WORKDIR /app

COPY --from=go-build /app/main ./

EXPOSE 3001

CMD ["./main"]
